# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- dev

pool:
  vmImage: ubuntu-latest

stages:  
- stage: Build  
  jobs:  
  - job: Build  
    steps:  
    - script: cd src
    - script: dotnet build -c Debug  
- stage: Test  
  jobs:  
  - job: UnitTest  
    steps:  
    - script: cd src
    - script: dotnet test Tests/**/*UnitTests/UnitTests.csproj -c Debug 
  - job: IntegrationTest  
    steps:  
    - script: cd src
    - script: dotnet test Tests/**/*IntegrationTests/IntegrationTests.csproj -c Debug
  - job: UITest  
    steps:  
    - script: cd src
    - script: dotnet test Tests/**/*.UITests/*.UITests.csproj -c Debug --collect:"XPlat Code Coevrage" --logger "trx" /p:CollectCoverage=true /p:CoverletOutput=./Tests/TestReports --% /p:CoverletOutputFormat=\"opencover,cobertura\"
