# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  autoCancel: true
  drafts: true
  branches:
    include:
    - dev
    exclude:
    - *

trigger:
  branches:
    exclude:
    - *

pool:
  vmImage: ubuntu-latest

variables:
  configuration: Release

stages:  
- stage: Build  
  jobs:  
  - job: Build  
    steps:
    - script: cd src
    - script: dotnet build ./SynergyISP.sln -c Release  
- stage: Test 
  dependsOn: Build
  jobs:  
  - job: UnitTest  
    steps:  
    - script: cd src
    - script: dotnet test ./Tests/Domain/UnitTests/UnitTests.csproj -c Release
    - script: dotnet test ./Tests/Application/UnitTests/UnitTests.csproj -c Release
  - job: IntegrationTest  
    steps:  
    - script: cd src && dotnet test ./Tests/**/*IntegrationTests/*IntegrationTests.csproj -c Release
  - job: UITest  
    steps:  
    - script: cd src && dotnet test ./Tests/**/*.UITests/*.UITests.csproj -c Release
